[tox]
envlist =
    py314-django52
    py314-django60
    py314-django61
    ruff
    ty

[testenv]
package = editable
dependency_groups = dev
passenv =
    DOCKER_*
deps =
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
    django61: django>=6.1,<6.2
commands =
    pytest

[testenv:ruff]
commands =
    ruff format --check --diff
    ruff check
deps =
    ruff

[testenv:ty]
commands =
    ty check
deps =
    ty
