from __future__ import annotations

import django
import pytest
from django.db import connection, models

from identityfield import (
    BigIdentityField,
    Identity,
    IdentityField,
    IdentityFieldBase,
)


@pytest.fixture(scope="module", autouse=True)
def unblocked_db(django_db_blocker):
    """`collect_sql` needs a connection, but never creates a table."""
    with django_db_blocker.unblock():
        yield


def column_sql(field, model_name, column="sequence"):
    """Return the column definition `CREATE TABLE` would emit for `field`."""
    model = type(
        model_name,
        (models.Model,),
        {
            "__module__": __name__,
            "Meta": type("Meta", (), {"app_label": "testapp"}),
            "sequence": field,
        },
    )
    with connection.schema_editor(collect_sql=True) as schema_editor:
        schema_editor.create_model(model)

    statement = schema_editor.collected_sql[0]
    return statement.split(f'"{column}" ', 1)[1].removesuffix(");")


@pytest.mark.parametrize(
    ("field_class", "column_type"),
    [
        (IdentityField, "integer"),
        (BigIdentityField, "bigint"),
    ],
)
def test_column_type_of_each_field_class(field_class, column_type):
    definition = column_sql(field_class(), f"Type{field_class.__name__}")

    assert definition.startswith(f"{column_type} GENERATED BY DEFAULT AS IDENTITY")


def test_identity_clause_is_configurable():
    definition = column_sql(IdentityField(identity=Identity.ALWAYS), "AlwaysClause")

    assert definition == "integer GENERATED ALWAYS AS IDENTITY"


def test_usual_field_options_still_work():
    field = IdentityField(
        db_column="seq", verbose_name="Sequence", help_text="counts up"
    )
    definition = column_sql(field, "Options", column="seq")

    assert definition == "integer GENERATED BY DEFAULT AS IDENTITY"
    assert field.verbose_name == "Sequence"
    assert field.help_text == "counts up"


def test_identity_is_keyword_only():
    """A positional verbose name used to end up in the identity clause."""
    with pytest.raises(TypeError):
        IdentityField("Sequence")  # ty: ignore[too-many-positional-arguments]


@pytest.mark.parametrize("option", ["expression", "output_field", "db_persist"])
def test_generated_field_plumbing_cannot_be_overridden(option):
    with pytest.raises(TypeError, match=option):
        IdentityField(**{option: models.Value(1)})


@pytest.mark.parametrize(
    ("option", "message"),
    [
        ({"default": 1}, "cannot have a default"),
        ({"editable": True}, "cannot be editable"),
    ],
)
def test_options_an_identity_column_cannot_honour_are_rejected(option, message):
    with pytest.raises(ValueError, match=message):
        IdentityField(**option)


def test_subclass_can_choose_its_column_type():
    class SmallIdentityField(IdentityFieldBase):
        output_field_class = models.SmallIntegerField

    definition = column_sql(SmallIdentityField(), "SubclassSmall")

    assert definition == "smallint GENERATED BY DEFAULT AS IDENTITY"


@pytest.mark.skipif(
    django.VERSION < (6, 1), reason="fields.W225 was added in Django 6.1"
)
def test_null_is_reported_as_having_no_effect():
    class Holder(models.Model):
        class Meta:
            app_label = "testapp"

        sequence = IdentityField(null=True)

    field = Holder._meta.get_field("sequence")
    warnings = field.check(databases=["default"])  # ty: ignore[unresolved-attribute]

    assert [warning.id for warning in warnings] == ["fields.W225"]
